image: gitpod/workspace-full
tasks:
  - init: yarn install
ports:
  - port: 3000
    onOpen: open-preview
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addBadge: true
    addLabel: true
vscode: 
  extensions:
    - esbenp.prettier-vscode
    - zignd.html-css-class-completion
    - eamodio.gitlens
    - hookyqr.beautify
    - ms-vscode.live-server
