image: nberlette/gitpod-enhanced:latest
tasks:
  - init: yarn install
  - command: yarn dev
ports:
  - port: 3000
    onOpen: open-preview
    name: "Live Preview"
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addBadge: true
    addLabel: true
vscode: 
  extensions:
    - esbenp.prettier-vscode
    - zignd.html-css-class-completion
