tasks:
  - init: yarn
  
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addBadge: true
    addLabel: true
    
vscode: 
  extensions:
    - esbenp.prettier-vscode
    - zignd.html-css-class-completion
    - eamodio.gitlens
    - hookyqr.beautify
    - ms-vscode.live-server
